name: Duplicate Code Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  duplicate-code:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
        coverage: none
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: plugin/vendor
        key: ${{ runner.os }}-php-8.1-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.1-composer-
    
    - name: Install dependencies
      run: |
        cd plugin
        composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run Code Quality Check
      run: |
        cd plugin
        composer dupe
